name: Invitation to the GitHub Community Organization
description: I would like to be part of the awesome community
title: "Please invite me to the GitHub Community Organization"
labels: [Invite me to the organization]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Where did you know about it?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](https://discord.gg/m5anDXXFr3)
        **You'll get an invitation as soon as you make the issue, please close the issue after you get the invite.**
