on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: GrowInCommunity
          label: Invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Welcome to the Organization! Please check your e-mail & make your membership public after you join from here https://github.com/orgs/GrowInCommunity/people'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
