on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite-on-label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: dev-protocol
          label: github-invitation
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: "Thank you, your Invitation has been sent. Please join our organization by accepting the invitaion, check you e-mail for the invite. Make sure you make your membership public after joining!"
        env:
          INVITE_TOKEN: ${{ secrets.DEV_INVITE_TOKEN }}
